@startuml
entity User {
    * userId : String [PK]
    * email : String
    * displayName : String
    * createdAt : Long
    * currentPoints : Int
}

entity Room {
    * roomId : String [PK]
    * name : String
    * description : String
    * code : String
    * expiration : String
    * betType : String
    * createdBy : String [FK -> User.userId]
    * isPublic : Boolean
}

entity BetCategory {
    * categoryId : String [PK]
    * roomId : String [FK -> Room.roomId]
    * categoryName : String
}

entity Message {
    * messageId : String [PK]
    * roomId : String [FK -> Room.roomId]
    * sender : String [FK -> User.userId]
    * message : String
    * timestamp : Long
}

entity Participant {
    * participantId : String [PK]
    * roomId : String [FK -> Room.roomId]
    * userId : String [FK -> User.userId]
    * betAmount : Int
    * betCategoryId : String [FK -> BetCategory.categoryId]
    * role : String
}

User ||--o{ Room : "creates"
Room ||--o{ Message : "contains"
Room ||--o{ Participant : "has"
Room ||--o{ BetCategory : "has"
Participant }|--|| User : "is linked to"
Participant }|--|| BetCategory : "places bet on"
@enduml
