@startuml

object Room1_RoomActivity {
    roomId = "room1"
    roomName = "Grades"
}

object Room2_RoomActivity {
    roomId = "room2"
    roomName = "Sheep betting"
}

object RoomAdapter1_RoomAdapter{
    rooms = "room1"
}

object ChatAdapter1_ChatAdapter {
    messages = "Hi everyone!"
}

object ChatAdapter2_ChatAdapter {
    messages = "I <~3 MATAN!"
}

object Message1_Message {
    sender = "Alice"
    message = "Hi everyone!"
    timestamp = 1627891234
}

object Message11_Message {
    sender = "fml"
    message = "H everyone!"
    timestamp = 12327891234
}
object Message2_Message {
    sender = "Bob"
    message = "Welcome to the chat."
    timestamp = 1627891240
}

RoomAdapter1_RoomAdapter --> Room1_RoomActivity
RoomAdapter1_RoomAdapter --> Room2_RoomActivity

Room1_RoomActivity --> ChatAdapter1_ChatAdapter
ChatAdapter1_ChatAdapter --> Message1_Message
ChatAdapter1_ChatAdapter --> Message11_Message
Room2_RoomActivity --> ChatAdapter2_ChatAdapter
ChatAdapter2_ChatAdapter --> Message2_Message

@enduml
